package com.eviahealth.eviahealth.meeting.models;


public enum MErrorCodes {

    MEETING_ERROR_SUCCESS (0, "MEETING_ERROR_SUCCESS"),
    MEETING_ERROR_INCORRECT_MEETING_NUMBER (1, "MEETING_ERROR_INCORRECT_MEETING_NUMBER"),
    MEETING_ERROR_TIMEOUT (2, "MEETING_ERROR_TIMEOUT"),
    MEETING_ERROR_NETWORK_UNAVAILABLE (3, "MEETING_ERROR_NETWORK_UNAVAILABLE"),
    MEETING_ERROR_CLIENT_INCOMPATIBLE (4, "MEETING_ERROR_CLIENT_INCOMPATIBLE"),
    MEETING_ERROR_NETWORK_ERROR (5, "MEETING_ERROR_NETWORK_ERROR"),
    MEETING_ERROR_MMR_ERROR (6, "MEETING_ERROR_MMR_ERROR"),
    MEETING_ERROR_SESSION_ERROR (7, "MEETING_ERROR_SESSION_ERROR"),
    MEETING_ERROR_MEETING_OVER (8, "MEETING_ERROR_MEETING_OVER"),
    MEETING_ERROR_MEETING_NOT_EXIST (9, "MEETING_ERROR_MEETING_NOT_EXIST"),
    MEETING_ERROR_USER_FULL (10, "MEETING_ERROR_USER_FULL"),
    MEETING_ERROR_NO_MMR (11, "MEETING_ERROR_NO_MMR"),
    MEETING_ERROR_LOCKED (12, "MEETING_ERROR_LOCKED"),
    MEETING_ERROR_RESTRICTED (13, "MEETING_ERROR_RESTRICTED"),
    MEETING_ERROR_RESTRICTED_JBH (14, "MEETING_ERROR_RESTRICTED_JBH"),
    MEETING_ERROR_WEB_SERVICE_FAILED (15, "MEETING_ERROR_WEB_SERVICE_FAILED"),
    MEETING_ERROR_REGISTER_WEBINAR_FULL (16, "MEETING_ERROR_REGISTER_WEBINAR_FULL"),
    MEETING_ERROR_DISALLOW_HOST_RESGISTER_WEBINAR (17, "MEETING_ERROR_DISALLOW_HOST_RESGISTER_WEBINAR"),
    MEETING_ERROR_DISALLOW_PANELIST_REGISTER_WEBINAR (18, "MEETING_ERROR_DISALLOW_PANELIST_REGISTER_WEBINAR"),
    MEETING_ERROR_HOST_DENY_EMAIL_REGISTER_WEBINAR (19, "MEETING_ERROR_HOST_DENY_EMAIL_REGISTER_WEBINAR"),
    MEETING_ERROR_WEBINAR_ENFORCE_LOGIN (20, "MEETING_ERROR_WEBINAR_ENFORCE_LOGIN"),
    MEETING_ERROR_EXIT_WHEN_WAITING_HOST_START (21, "MEETING_ERROR_EXIT_WHEN_WAITING_HOST_START"),
    MEETING_ERROR_REMOVED_BY_HOST (22, "MEETING_ERROR_REMOVED_BY_HOST"),
    MEETING_ERROR_HOST_DISALLOW_OUTSIDE_USER_JOIN (62, "MEETING_ERROR_HOST_DISALLOW_OUTSIDE_USER_JOIN"),
    MEETING_ERROR_INVALID_ARGUMENTS (99, "MEETING_ERROR_INVALID_ARGUMENTS"),
    MEETING_ERROR_UNKNOWN (100, "MEETING_ERROR_UNKNOWN"),
    MEETING_ERROR_INVALID_STATUS (101, "MEETING_ERROR_INVALID_STATUS"),
    MEETING_ERROR_JMAK_USER_EMAIL_NOT_MATCH (1143, "MEETING_ERROR_JMAK_USER_EMAIL_NOT_MATCH"),
    MEETING_ERROR_APP_PRIVILEGE_TOKEN_ERROR (500, "MEETING_ERROR_APP_PRIVILEGE_TOKEN_ERROR");

    private int code;
    private String msg;

    public int getCode() {
        return this.code;
    }

    public void setCode(int var1) {
        this.code = var1;
    }

    public String getMsg() {
        return this.msg;
    }

    public void setMsg(String var1) {
        this.msg = var1;
    }

    private MErrorCodes(int var3, String var4) {
        this.code = var3;
        this.msg = var4;
    }

    public static MErrorCodes toErrorCode(int var0) {
        MErrorCodes[] var1 = values();
        int var2 = var1.length;

        for(int var3 = 0; var3 < var2; ++var3) {
            MErrorCodes var4 = var1[var3];
            if (var4.getCode() == var0) {
                return var4;
            }
        }

        return MEETING_ERROR_UNKNOWN;
    }
}
